### ISSUE TITLE
Context-dependent progress bar color

### ISSUE THREAD

**Issue by desember** [KikiManjaro/MarioProgressBar#2]
Hi,

Is it possible to alter brick wall progress bar color based on current context? 

For example, when unit tests are running default Intellij progress bar is green until first failed test. Then it changes color to red. Brick wall is always dark red. Sometimes it is confusing as you cannot simply tell whether there are test failures or not.

For example, [here](https://www.spriters-resource.com/nes/supermariobros/sheet/65962/) you can find different color bricks.
 
Thank you.

**Comment by KikiManjaro** [comment]
Hi ! 
As far as i know Jetbrains IDE Progress Bars are not able to handle context events like errors. I'll see if i can do something :) Thank for the idea.
