### ISSUE TITLE
Fix typo in code

### ISSUE THREAD

**Issue by roon-replica** [KikiManjaro/MarioProgressBar#5]
Hi, I am using mario status bar well. 
There is typo in variable name In MarioProgressBarSettingsState.java. I want to change code 
from
```java
public MBCharacter selectedCharacted = MARIO;
``` 
to
```java
public MBCharacter selectedCharacter = MARIO;
```

**Comment by KikiManjaro** [comment]
Thanks !
You can do it if you want, or i'll fix that in the next release :)

**Comment by roon-replica** [comment]
I made a pull request!
