### ISSUE TITLE
Plugin is not working in the latest update

### ISSUE THREAD

**Issue by diovan-termonos** [KikiManjaro/MarioProgressBar#7]
Plugin is not working in the latest IntelliJ/PHPStorm update:

IntelliJ IDEA 2023.3 (Ultimate Edition)
Build #IU-233.11799.241, built on December 2, 2023
Licensed to Diovan De Pin
Subscription is active until March 2, 2024.
Runtime version: 17.0.9+7-b1087.7 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.1.2
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.browser.jcef.gpu.disable=true
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
  ide.images.show.chessboard=true
Non-Bundled Plugins:
  manjaro.mpb (1.8)
  com.intellij.plugins.xwinkeymap (211.4961.30)
  com.intellij.plugins.macoskeymap (232.6095.10)
  Statistic (4.2.7)
  com.jetbrains.packagesearch.intellij-plugin (233.11799.196)
  org.jetbrains.plugins.docker.gateway (233.11799.244)
  com.jetbrains.php (233.11799.241)
Kotlin: 233.11799.241-IJ

**Comment by kLeZ** [comment]
+1

**Comment by GelHowell-SNS** [comment]
+1

**Comment by Ollitod** [comment]
+1

**Comment by Pplociennik** [comment]
+1

**Comment by parasoLT-DF** [comment]
+1

**Comment by samsterpiece** [comment]
+1 to this as well

**Comment by SeifBh** [comment]
+1 on IntelliJ IDEA2023.3.2 (Ultimate Edition)

**Comment by diovan-termonos** [comment]
Guess who is back: It's a me, Mario!.
